trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - green-deployment-pipeline.yml

pool: bharathi-bg-agpool

stages:
- stage:
  jobs:
  - job: Deploy
    displayName: Green Deployment
    pool: bharathi-bg-agpool
    steps:
    - bash: |
        export VM_IP="`hostname -i`"
        echo $VM_IP
        echo `pwd`
        echo "##vso[task.setvariable variable=SERVICE_IP;]$VM_IP"
        cat $(System.DefaultWorkingDirectory)/blue-green-tf/green-tf/configs.txt
        traffic_split_per=`cat $(System.DefaultWorkingDirectory)/blue-green-tf/green-tf/configs.txt`
        export TRAFFIC_SPLIT_PERCENTAGE=`expr $traffic_split_per`
        echo "##vso[task.setvariable variable=TRAFFIC_SPLIT_PERCENTAGE;]$TRAFFIC_SPLIT_PERCENTAGE"
      displayName: 'Configure Backend Service IP'
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      inputs:
        terraformVersion: '0.13.5'
    - task: TerraformCLI@0
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/blue-green-tf/green-tf'
        allowTelemetryCollection: false
        backendType: selfConfigured
      displayName: 'terraform init'
    - task: TerraformCLI@0
      displayName: 'terraform plan'
      inputs:
        command: plan
        workingDirectory: '$(System.DefaultWorkingDirectory)/blue-green-tf/green-tf'
        environmentServiceName: 'NSDev GWY CA raghul.christus@citrix.com(23b03d6f-b164-4527-9acd-595d97060283)'
        commandOptions: '-var "backend_service=$(SERVICE_IP)" -var "username=nsroot" -var "password=nsroot@12345" -var "traffic_split_percentage=$(TRAFFIC_SPLIT_PERCENTAGE)"'
        allowTelemetryCollection: false
    - bash: |
        sleep 120
    - task: TerraformCLI@0
      displayName: 'terraform apply'
      inputs:
        command: apply
        workingDirectory: '$(System.DefaultWorkingDirectory)/blue-green-tf/green-tf'
        environmentServiceName: 'NSDev GWY CA raghul.christus@citrix.com(23b03d6f-b164-4527-9acd-595d97060283)'
        commandOptions: '-var "backend_service=$(SERVICE_IP)" -var "username=nsroot" -var "password=nsroot@12345" -var "traffic_split_percentage=$(TRAFFIC_SPLIT_PERCENTAGE)"'
        allowTelemetryCollection: false
      enabled: True
      
    - task: TerraformCLI@0
      displayName: 'terraform destroy'
      inputs:
        command: destroy
        workingDirectory: '$(System.DefaultWorkingDirectory)/blue-green-tf/green-tf'
        environmentServiceName: 'NSDev GWY CA raghul.christus@citrix.com(23b03d6f-b164-4527-9acd-595d97060283)'
        commandOptions: '-var "backend_service=$(SERVICE_IP)" -var "username=nsroot" -var "password=nsroot@12345" -var "traffic_split_percentage=$(TRAFFIC_SPLIT_PERCENTAGE)"'
        allowTelemetryCollection: false
      enabled: False
      
    - task: TerraformCLI@0
      displayName: 'terraform apply copy'
      inputs:
        command: destroy
        workingDirectory: '$(System.DefaultWorkingDirectory)/blue-green-tf/green-tf'
        environmentServiceName: 'NSDev GWY CA raghul.christus@citrix.com(23b03d6f-b164-4527-9acd-595d97060283)'
        commandOptions: '-var "backend_service=$(SERVICE_IP)" -var "username=nsroot" -var "password=nsroot@12345" -var "traffic_split_percentage=$(TRAFFIC_SPLIT_PERCENTAGE)"'
        allowTelemetryCollection: false
      enabled: False
      
