trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - blue-green-tf/azure_pipelines/green-deployment-pipeline.yml
    - blue-green-tf/azure_pipelines/config/teardown-destroy-input-generator.py
    - blue-green-tf/azure_pipelines/teardown-pipeline.yml
    - blue-green-tf/azure_pipelines/config/teardown.json

pool: bharathi-bg-agpool

stages:
- stage:
  jobs:
  - job: Deploy
    displayName: Green Deployment
    pool: bharathi-bg-agpool
    steps:
    - task: PythonScript@0
      displayName: 'Update Pipeline variables'
      inputs:
        scriptPath: '$(System.DefaultWorkingDirectory)/blue-green-tf/azure_pipelines/config/read_setup_config.py'
        arguments: --config_file '$(System.DefaultWorkingDirectory)/blue-green-tf/azure_pipelines/config/setup_config.json'
    
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '0.13.5''

    - task: TerraformCLI@0
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(TERRAFORM_SCRIPT_PATH)'
        allowTelemetryCollection: false
        backendType: selfConfigured
      displayName: 'terraform init'
    - task: TerraformCLI@0
      displayName: 'terraform plan'
      inputs:
        command: plan
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(TERRAFORM_SCRIPT_PATH)'
        environmentServiceName: 'NSDev GWY CA raghul.christus@citrix.com(23b03d6f-b164-4527-9acd-595d97060283)'
        commandOptions: '-var "backend_service=$(SERVICE_IP)" -var "username=$(ADC_USERNAME)" -var "password=$(ADC_PASSWORD)" -var "traffic_split_percentage=$(TRAFFIC_SPLIT_PERCENTAGE)"'
        allowTelemetryCollection: false
    - task: TerraformCLI@0
      displayName: 'terraform apply'
      inputs:
        command: apply
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(TERRAFORM_SCRIPT_PATH)'
        environmentServiceName: 'NSDev GWY CA raghul.christus@citrix.com(23b03d6f-b164-4527-9acd-595d97060283)'
        commandOptions: '-var "backend_service=$(SERVICE_IP)" -var "username=$(ADC_USERNAME)" -var "password=$(ADC_PASSWORD)" -var "traffic_split_percentage=$(TRAFFIC_SPLIT_PERCENTAGE)"'
        allowTelemetryCollection: false
      enabled: True
