trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - blue-green-tf/azure_pipelines/green-deployment-pipeline.yml
    - blue-green-tf/azure_pipelines/teardown-pipeline.yml
    include:
    - blue-green-tf/azure_pipelines/config/teardown.json

pool: bharathi-bg-agpool

stages:
- stage:
  jobs:
  - job: TearDown
    displayName: Delete Deployment
    pool: bharathi-bg-agpool
    steps:
    - task: PythonScript@0
      displayName: 'Update Pipeline variables for deleting existing config on ADC'
      inputs:
        scriptPath: '$(System.DefaultWorkingDirectory)/blue-green-tf/azure_pipelines/config/read_teardown_config.py'
        arguments: --config_file $(System.DefaultWorkingDirectory)/blue-green-tf/azure_pipelines/config/teardown.json
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      inputs:
        terraformVersion: '0.13.5'
      displayName: 'Install Terraform'