trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - blue-green-tf
    - canary-pipeline.yaml
    - green-deployment-pipeline.yml

pool: aks-agent-pool

stages:
- stage:
  jobs:
  - job: Deploy
    displayName: Canary Deployment
    pool: aks-agent-pool
    steps:
    - task: Kubernetes@0
      displayName: 'Deploy Application'
      inputs:
        kubernetesServiceConnection: 'bharathi-cn-aks-svc-con'
        command: apply
        useConfigurationFile: true
        configuration: '$(System.DefaultWorkingDirectory)/k8s_yamls/simple_canary/canary'
